version: '3.7'

services:
  postgres:
    image: debezium/example-postgres
    container_name: postgres
    ports:
      - 5433:5432
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "max_replication_slots=4"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=admin"
    networks:
      - ${GLOBAL_NETWORK:-postgres}
