name: Commit Stage
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: skyglass-restaurant
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: ~/.m2
      - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "${{ github.workspace }}"
          fail-build: false
          severity-cutoff: high
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Build, unit tests and integration tests
        run: |
          mvn clean install -DskipTests
  package:
    name: Package and Publish
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [ build ]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: ~/.m2
      - name: Build container image
        run: |
          cd customer-service/customer-container
          mvn spring-boot:build-image \
            -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/customer-service:${{ env.VERSION }}
          cd ../../
          cd order-service/order-container
          mvn spring-boot:build-image \
            -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/order-service:${{ env.VERSION }}
          cd ../../
          cd payment-service/payment-container
          mvn spring-boot:build-image \
            -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/payment-service:${{ env.VERSION }} 
          cd ../../
          cd restaurant-service/restaurant-container
          mvn spring-boot:build-image \
            -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/restaurant-service:${{ env.VERSION }}                          
      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        run:  |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/customer-service:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/order-service:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/payment-service:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/restaurant-service:${{ env.VERSION }}
      - name: Publish container image (latest)
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/customer-service:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/customer-service:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/customer-service:latest
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/order-service:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/corder-service:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/order-service:latest
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/payment-service:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/payment-service:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/payment-service:latest
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/restaurant-service:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/restaurant-service:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/restaurant-service:latest